spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/shafiq_test?useSSL=false
    username: root
    password: root
  jpa:
    generate-ddl: true
    database: mysql
    #    hibernate:
    #      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate.format_sql: true
#      hibernate.generate_statistics: true
hibernate:
  dialect: org.hibernate.dialect.MySQLDialect
  query:
    in_clause_parameter_padding: true
logging:
  level:
    org.springframework.security: debug

# JWT Config
app:
  jwt:
    secretKey: securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecure
    tokenPrefix: Bearer
    tokenExpirationAfterDays: 10
security:
  oauth2:
    client:
      client-id: 151374428837-jpnaa79bu3evqiuil8e9lvcgtk58hh5h.apps.googleusercontent.com
      client-secret: nX0REN_8Uf5So4o3_rcHRetr
      accessTokenUri: https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: profile
    resource:
      userInfoUri: https://www.googleapis.com/userinfo/v2/me
      preferTokenInfo: false

