spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/shafiq_test?useSSL=false
    username: root
    password: root
  jpa:
    generate-ddl: true
    database: mysql
    #    hibernate:
    #      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate.format_sql: true
#      hibernate.generate_statistics: true
hibernate:
  dialect: org.hibernate.dialect.MySQLDialect
  query:
    in_clause_parameter_padding: true
logging:
  level:
    org.springframework.security: debug

# JWT Config
app:
  jwt:
    secretKey: securesecuresecuresecuresecuresecuresecuresecuresecuresecuresecure
    tokenPrefix: Bearer
    tokenExpirationAfterDays: 10
